{% set version = "4.13.2" %}
package:
  name: antlr
  version: {{ version }}

source:
  url: https://github.com/antlr/antlr{{ version[0] }}/archive/{{ version }}.tar.gz
  sha256: 9f18272a9b32b622835a3365f850dd1063d60f5045fb1e12ce475ae6e18a35bb

build:
  number: 0

requirements:
  build:
    - maven
  run:
    - openjdk

test:
  commands:
    - antlr4
    - grun

about:
  home: https://www.antlr.org
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: ANother Tool for Language Recognition (ANTLR).
  description: |
    ANTLR (ANother Tool for Language Recognition) is a powerful parser generator 
    for reading, processing, executing, or translating structured text or binary 
    files.
  dev_url: https://github.com/antlr/antlr4
  doc_url: https://github.com/antlr/antlr4/blob/master/doc/index.md

extra:
  recipe-maintainers:
    - tobias-fischer
    - ocefpaf
    - kwilcox
    - bollwyvl
    - zklaus
