{% set version = "4.7" %}
{% set name = "antlr4" %}

package:
  name: antlr
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/antlr/antlr4/archive/4.7.tar.gz
  sha256: 30d1ea7b2f591ba1d7cacf3b4c1232df98783a8b64d5421eaf6bf1d4f7fcf478

build:
  number: 0

requirements:
  build:
    - maven
    - python >=3.6,<3.7
  run:
    - openjdk

test:
  commands:
    - antlr4

about:
  home: http://www.antlr.org
  license: BSD-3-clause
  summary: ANother Tool for Language Recognition (ANTLR).
  description: >
    ANTLR (ANother Tool for Language Recognition) is a powerful parser
    generator for reading, processing, executing, or translating
    structured text or binary files.

extra:
  recipe-maintainers:
    - ocefpaf
    - kwilcox
