{% set name = "antlr" %}
{% set major_version = "4" %}
{% set minor_version = "8" %}
{% set version = major_version + "." + minor_version %}
{% set revision = "1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/{{ name }}/{{ name }}{{ major_version }}/archive/{{ version }}.tar.gz
  sha256: 992d52444b81ed75e52ea62f9f38ecb7652d5ce2a2130af143912b3042a6d77e

build:
  number: 1

requirements:
  build:
    - maven
  run:
    - openjdk

test:
  commands:
    - antlr4
    - grun

about:
  home: https://www.antlr.org
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: ANother Tool for Language Recognition (ANTLR).
  description: >
    ANTLR (ANother Tool for Language Recognition) is a powerful parser
    generator for reading, processing, executing, or translating
    structured text or binary files.
  dev_url: https://github.com/antlr/antlr4
  doc_url: https://github.com/antlr/antlr4/blob/master/doc/index.md

extra:
  recipe-maintainers:
    - ocefpaf
    - kwilcox
    - bollwyvl
