package:
    name: antlr
    version: 2.7.7

source:
    fn: antlr-2.7.7.tar.gz
    url: http://www.antlr2.org/download/antlr-2.7.7.tar.gz
    sha256: 853aeb021aef7586bda29e74a6b03006bcb565a755c86b66032d8ec31b67dbb9
    patches:
        - CharScanner.patch

build:
    number: 2
    skip: True  # [win]

test:
    commands:
        - antlr-config --version

about:
    home: http://www.antlr2.org/
    license: BSD-3-clause and GPL-3.0 and Public Domain
    summary: 'ANother Tool for Language Recognition (ANTLR).'

extra:
    recipe-maintainers:
        - ocefpaf
        - kwilcox
