build_platform:
  osx_arm64: osx_64
conda_forge_output_validation: true
github:
  branch_name: main
  tooling_branch_name: main
provider:
  linux_aarch64: default
  linux_ppc64le: default
  win: azure
test_on_native_only: true
bot:
  abi_migration_branches:
  - v4.9.3
  - osx-arm64-4.8
conda_build:
  pkg_format: '2'
