travis:
  secure:
    BINSTAR_TOKEN: Jr3Cpl4dItUiotEuo9YtVaqnzt6DRS/ox16OuIqz4bUlCSFzihTGDl/QIJ9qDCKra+97oShVfR948B/uq/mT8aSUeR8sm3LPUvhaR4lUrxPwmuOBVZW1jkvuAjw4be2bT7tzKZosocX/1qc8Ey4I5AfL0l1hdKV+//JcuFMh1Mbo3jypqzGtxtU6itktFwzZiv50tFLUeLGxUesNK0+kRY5k7DblSwjDKPr8Sp2acad9CRKC1uyAFjUpNUFCCdPvt64RANOhvJes/ZWeE5SGeXLngs4RzY50iZ4mUIp1v3bNsQUBV9sq9Y5h+rH7nMwUh9Vj5sPlfitZasPqpw9d0gjAxx1LeA/rWSvZ+EdiF2g9oJiyJI0Y7N0oA6XZnx/MSCUfMK5eG2Qjg5InDtQ6VyqZXaypb6teyS6Z4Jsn3sDytZ5u+lpwWN+cVKRcxP0IFoJs42jw+Lfev96iFVYkc2vaTqzZW3HGtGu1GWx7Cwn0y0sRANE9HPweXFXhUu8Xb+nOjKUOunKSDTxIe7vEhT5QH/bPLOXTBla5AMifc8+V4XwpESmA3jZp/h5Rm7h39osr5PIfoA5mXXFoBnRD8WafDdtfoGlVj53XthRcJzShQa+2aC9Q/Vb5dxqF7ejuyky86frGffpNkwJfZgmnB/vCNIlFzsQ/BYRWaUuvWNg=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
